### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [Kijpokin/g-search#7]
Hello Mackie 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I will be the reviewer for the code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

It appears, however, that many core features are missing from this submission (see below):

![image](https://user-images.githubusercontent.com/696529/169731838-73b8d674-e383-457e-a9de-98f753618852.png)

The application currently only provides a list of matched keywords and the total of result found:

![image](https://user-images.githubusercontent.com/696529/169731991-6839d82f-28d0-4207-92a3-3bd3619963a7.png)
 
Therefore, the submission is significantly incomplete, thus it will impact the overall outcome negatively.

**Comment by Kijpokin** [comment]
@olivierobert Hi, thanks for your thoughtful reviewing, i missed important information which is really needed. my first understood idea is the process want to test how we design, and architect the apps in overall data flow.

The details could be add, let me complete the results, I will update the information following the requirement.

**Comment by Kijpokin** [comment]
Updated results in https://github.com/Kijpokin/g-search/pull/10

**Comment by olivierobert** [comment]
Thank you for taking part in the code review process. It is now time to end this stage of the recruitment process. Our feedback will be provided to you by email.
