### ISSUE TITLE
[Feature] Uploaded keywords are not processed immediately

### ISSUE THREAD

**Issue by olivierobert** [Kijpokin/g-search#8]
## Issue

When upload a file with multiple keywords, the application only parses the keywords but no search is executed. The user has to click on the parsed keywords to see the search results:

![image](https://user-images.githubusercontent.com/696529/169734002-822bd0b7-e7ca-4252-a5d8-d0c47f9c301a.png)

🙈  Also note that empty lines (EOF) are not processed and shows as an empty link

## Expected

The uploaded keywords are stored in the database. Then, a process executes the search for each keywords. Upon successfully, performing the search the results are stored in the database. In the mean time, the user must see the search status for each keyword (e.g., `pending`, `completed`, or `failed`).

**Comment by Kijpokin** [comment]
@olivierobert 
Sure, currently idea behind keywords upload is depends on `column` which is will count the keyword start from 2nd rows.

Thanks for raised issues, I will update to support the cases.

**Comment by Kijpokin** [comment]
Updated in #10

**Comment by olivierobert** [comment]
I reviewed the changes and now there is scraping in place 👏 

However, note that while this works great for one keyword, there is still no queue system when uploading a file with many keywords. 

```ts
export async function batchUploadKeywords({ keywords, userId }: { keywords: string[]; userId: User['id'] }) {
  let batchKeywords = [];

  for (let body of keywords) {
    const { totalLink = 0, totalAdword = 0, stats = '', html = '' } = await getSearchResult(body);

    batchKeywords.push({
      body,
      userId,
      totalAdword,
      totalLink,
      stats,
      html,
    });
  }

  return prisma.keyword.createMany({
    data: batchKeywords,
    skipDuplicates: true,
  });
}
```

The scraping and the persistence of keywords to the database should be decoupled i..e, the keywords should first be stored in the DB and then picked up by a queue system for processing or a background job should be schedule job for each keyword. In the current implementation, if any unhandled error occurs, the remaining keywords would be lost.
