### ISSUE TITLE
[Feature] Extract business logic from routes

### ISSUE THREAD

**Issue by olivierobert** [Kijpokin/g-search#9]
## Issue

While routes are first citizens in Remix, putting all business logic in routes  result in complex routes files, thus causing maintainability and testability issues.

## Expected

Extract the Google search code to a service object or function e.g., `app/services` or `lib/services` (if grouping by boundaries/context is preferred). The same would apply also for the keyword parsing. These small units of code could then be tested independently 💡

**Comment by Kijpokin** [comment]
@olivierobert 

Thanks for flagging, this is a great idea though!. basically remix controlled start from **routes**, which is a page logic among server-side rendering in **loader** and **action**, it's a flexible option to put the along in a file or split to the other files.

I would move business logic to the other folders.

**Comment by Kijpokin** [comment]
Updated in #11

**Comment by olivierobert** [comment]
Thank you for working on the changes 🙏 

Additionally, the CSV file parsing could also have been moved to services 💡
